# External Ansible roles required by this repository

- name: ome.basedeps
  src: https://github.com/pwalczysko/ansible-role-basedeps/
  version: fix-repo-rhel

- name: ome.ice
  version: 4.3.0

- name: ome.java
  version: 2.2.0

- name: ome.omero_common
  version: 0.4.0

- name: ome.omero_server
  src: https://github.com/khaledk2/ansible-role-omero-server
  version: fix_include


- name: ome.postgresql_client
  version: 0.3.0
